
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: planningPoker_api_development


test:
  <<: *default
  database: planningPoker_api_test

production:
  <<: *default
  database: planningPoker_api_production
  username: planningPoker_api
  password: <%= ENV['PLANNINGPOKER_API_DATABASE_PASSWORD'] %>
